### ISSUE TITLE
Access granted doesn't include write permissions

### ISSUE THREAD

**Issue by mspanish** [Pomax/node-flickrapi#102]
Well your tool is the only one of about 4 that appears close to working :) - but I redid the auth and noticed that it said the app would NOT have write access - which probably explains why the uploads are failing. Do I need to adjust something? I am using this to authenticate, having set the keys already:

```
Flickr.authenticate(flickrOptions, function(error, flickr) {
  // we can now use "flickr" as our API object
});
```
thanks for your work on this, it must have taken a lot of work!

**Comment by Pomax** [comment]
Just to rule out a missing conf option, did you set the `FLICKR_PERMISSIONS` variable to `write` in your .env file?

**Comment by mspanish** [comment]
thanks I did change to "read" and all works great - thank you!!!

**Comment by Pomax** [comment]
if you change the permission, remember to remove the stored tokens, so that flickr-mirror can get a new token specific to that permission level (Flickr won't let you use "read" tokens for "read/write" or "read/write/delete", etc)

**Comment by mspanish** [comment]
ok thanks very much, lovely work here.
