### ISSUE TITLE
control which image sizes are downloaded during downsync

### ISSUE THREAD

**Issue by Pomax** [Pomax/node-flickrapi#20]
possibly a comma separated .env list or the like!

**Comment by Pomax** [comment]
not actually all the needed, closing for now

**Comment by siriux** [comment]
Hi,

Is this going to be implemented? I would like to control which sizes are downloaded  (Meta Only, Single Size, Multiple Sizes, All Sizes).

This would be really useful for apps that need the meta data, but want to download images on demand, and cache some things, but not everything.

Cheers

**Comment by Pomax** [comment]
I wasn't going to add this myself anymore, since a downsync is a straight up mirror; changing which images are downloaded seemed odd in retrospect. Especially since for non-downsyncing purposes the plain API calls let you be specific about which image sizes you want.

For apps that need meta data but not images, it feels like those do not want downsyncing, but should simply implement their own logic for getting the data they need using plain API calls?

**Comment by siriux** [comment]
Yes, you are right that it's possible to do it with the API calls. Still, I think that a partial mirror can be useful in many cases (e.g. you only want originals or thumbnails) and it would share 99% of the implementation with the full mirror (save and recover to files, check modification dates, ...).

But of course, this is just my opinion.

Cheers

**Comment by Pomax** [comment]
you need at least the original, large, and thumbnails, to build a browsable mirror, looking at the sizes for my flickr mirror, the rest of the data is still "a bit", but not enough to say we're going to save lots of time and space by not just downloading them anyway and then having them available for things like http://pomax.github.io/flickrmirror/

**Comment by siriux** [comment]
Maybe you are right, and for my use case it's better to use the API directly.

Thanks for the link to flickrmirror, I didn't know about it.
