### ISSUE TITLE
How to have two simultaneous flickr objects?

### ISSUE THREAD

**Issue by NeilRickards** [Pomax/node-flickrapi#41]
Likely I'm not using the library correctly, but the following code results in lots of blank lines printed to console then it appears to hang.  Behaviour is the same with authenticate(...)

var Flickr = require("flickrapi");

Flickr.tokenOnly({
    api_key: MY_API,
    secret: MY_SECRET,
    user_id: "46936561@N00",
}, function(err, flickr) {});

Flickr.tokenOnly({
    api_key: MY_API,
    secret: MY_SECRET,
    user_id: "23323767@N06",
}, function(err, flickr) {});

**Comment by AnmAtAnm** [comment]
Seeing similar issues. Ran Neil's original code, and see the same annoying newlines as I see in my own. Did 'npm update', using latest 0.3.28.
