### ISSUE TITLE
Hide progress bars (enhancement)

### ISSUE THREAD

**Issue by benlowry** [Pomax/node-flickrapi#44]
The progress bars (at least on server-side, OS X 10.10 / NodeJS v0.10.32 in iTerm2) interferes with parsing or just reading all other terminal output.  Please add a way to hide or disable the progress bars.

![screenshot 2014-11-28 14 10 49](https://cloud.githubusercontent.com/assets/2373805/5232050/480180be-770b-11e4-9265-5c96d72e8f91.png)

**Comment by Pomax** [comment]
https://github.com/Pomax/node-flickrapi/pull/45 landed, forgot to crosslink/close
