### ISSUE TITLE
Compile Problem

### ISSUE THREAD

**Issue by bagerakbay** [Pomax/node-flickrapi#51]
Hi, 
I am a totally newbie in js.

when I try to compile the project , I get
```
compile.js:13
      flickrOptions = env.get("FLICKR"),
                          ^
TypeError: Object false has no method 'get'
    at compile.js:13:27
    at Object.<anonymous> (node-flickrapi-master\compile.js:153:2)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```

any idea why this might happen ?
I am on windows 7.

**Comment by Pomax** [comment]
it looks like you don't have an `.env` file set up. Did you remember to copy the `env.sample` file as `.env`?

**Comment by bagerakbay** [comment]
oh sorry, it is not possible to name a file ".env" from gui in windows, so I thought it was something else. I did it through command prompt. Thanks a lot.

**Comment by Pomax** [comment]
Hmm, it should be - if I select a file in windows explorer and hit F2, I can change both the file name and extension. If I use the mouse by using a long click, I can still change both, but it'll only have auto-selected the filename part. Which GUI are you using?

(I personally like Total Commander, but it's technically shareware)

**Comment by bagerakbay** [comment]
Well if you select a file, hit f2, and give no file name. You get an error "You must type a filename".
At least, it does that on windows 7.

**Comment by Pomax** [comment]
right, but `.env` is definitely a filename. F2, clear everything, type .env, hit enter (I'm also in win7, that seems to work for me)
