### ISSUE TITLE
flickr.stats.photo.getGraphData doesn't exist

### ISSUE THREAD

**Issue by ryanshawty** [Pomax/node-flickrapi#56]
Every time a Flickr.tokenOnly is called it's send a request for a method called flickr.stats.photo.getGraphData which apparently doesn't exist. This only happens on my production server, doesn't happen locally (using same key/secret)

**Comment by Pomax** [comment]
Nowhere in the code is there anything that calls `getGraphData`, do you have a more detailed description of what you see happening, and have you searched the code you use on top of the API for any mention of that method?

**Comment by ryanshawty** [comment]
I deleted the stored methods data in data/flickr and its working fine now
so not sure what the cause was.

**Comment by Pomax** [comment]
hm, weird. I'll keep an eye out for mystery behaviour on my own flickr mirrors (which all rely on this API), if I catch them doing something similar I'll file an issue with whatever details I can gather.
