### ISSUE TITLE
Error initialising the flickr API

### ISSUE THREAD

**Issue by mattmcneeney** [Pomax/node-flickrapi#58]
It is taking a long time (around 2 minutes) to cache the available methods in the Flickr API. When the caching finally completes, an error is returned:
```
[Error: HTTP Error: no response for url [https://api.flickr.com/services/rest/?api_key=52c4faaf0c876aed4184fa2dca98ce12&format=json&method=flickr.reflection.getMethodInfo&method_name=flickr.photosets.addPhoto]]
```
Is anyone else seeing this problem?

Thanks!

**Comment by Pomax** [comment]
Hm, I haven't seen that happen before but it looks like an HTTP timeout issue. Is this consistent or intermittent? (if consistent, do you have the option to try it from a different network, like work vs home or the like to see if it's universal?)

**Comment by Pomax** [comment]
closing due to insufficient information to debug.
