### ISSUE TITLE
Image upload response is success but no image is being uploaded

### ISSUE THREAD

**Issue by sanjeevkumarraob** [Pomax/node-flickrapi#59]
i tried using flicker api in angular-fullstack and i am able to authenticate. But when i tried to upload photos, i am getting an empty array as result. flickr authentication included delete permission.
output:
photos uploaded []

I am not getting any error and no images are being uploaded as well. Kindly guide me

**Comment by sanjeevkumarraob** [comment]
What i found is the user_id of the flickr account is different from the authorisation code returned from api call

**Comment by Pomax** [comment]
most definitely. Only the authenticated user has the authentication rights, so if you want to upload "on behalf of user X", you'll need to authenticate as them.

**Comment by sanjeevkumarraob** [comment]
how to do that?. i am trying to upload photos to my flickr  account using node server. Whenever i authenticate i am getting a different authentication code like 123-456-789 which has upload permissions.

But my userid of my account maybe say 78967543@N04

how can i upload the pictures to this particular userid?

**Comment by Pomax** [comment]
you use the authentication code to negotiate *actual* credentials, which are in the form of an authentication token and secret. The username `78967543@N04` is a correct username, but during negotiation you will receive additional values to use in future negoations.

See https://github.com/Pomax/node-flickrapi#an-example-run for a concrete example of this.
