### ISSUE TITLE
Can't get private photos

### ISSUE THREAD

**Issue by fredericd** [Pomax/node-flickrapi#60]
I may be my fault. I may misuse your API, but I can't get my private photos using you API, neither with `flickr.people.getPhotos`, nor with `flickr.photos.search` call. Since I'm correctly authenticate, and I'm the owner of requested photos, I should get them accordingly to Flick API doc. I can't find what I'm doing wrong. Does it sound familiar to you?

**Comment by Pomax** [comment]
hmm, hadn't run into that before - are you authenticating with proper oauth credentials, or with the "tokenOnly" APi token?

**Comment by fredericd** [comment]
Thanks for you quick reply! Here is the code I use:

```javascript
#!/usr/bin/env node

var fs         = require('fs'),
    util       = require('util'),
    flickrapi  = require("flickrapi");

var config = eval('('+fs.readFileSync('config.json','utf8')+')');
exports.config = config;

flickrapi.authenticate(config.flickr, function(error, flickr) {
    // we can now use "flickr" as our API object
    console.log("Autentification OK");
    console.log(util.inspect(flickr.options, false, null));
    flickr.people.getPhotos({
        api_key: flickr.options.api_key,
        user_id: flickr.options.user_id,
        page: 1,
        per_page: 100
    }, function(err, result) {
        console.log(util.inspect(result, false, null));
    });
});
```
I got `access_token` and `access_toke_secret` correctly set in my `config.json` file. As soon as I turn some photo public, they appear in `result` returned by `flickr.people.getPhotos`. 

I will retry from another Linux box. If you have any idea...

**Comment by Pomax** [comment]
hm, that should work, once you have an access token your API requests should return "all photos you can see". Can you try passing in `privacy_filter: 5` as option? Normally that's what it uses already, but maybe it's somehow not picking up on that?

**Comment by fredericd** [comment]
Thanks for your suggestion, I had already tried indeed, without success. I still have to retry from another linux box.

**Comment by Pomax** [comment]
then now it's a bug, and I'll try to see what it's doing for private photos on my account. Thanks for helping rule out some things

**Comment by Pomax** [comment]
this turns out to be based on the Flickr API's information on whether or not a function requires authentication. https://www.flickr.com/services/api/flickr.people.getPhotos.html does not *require* authentication, but without authenticating it won't have an authorised user for which to get private photos either, so let me update the call handling so that you can always force authentication in, even if a method does not *require* authentication, but behaves differently if you do anyway.

**Comment by Pomax** [comment]
fixed, v0.3.30 pushed to npm.

Use `authenticated: true` as new, optional argument to API calls to force authentication to be used for API calls that can also run without authentication.

**Comment by fredericd** [comment]
Thanks. I confirm it works! I wasn't that far away from a solution on my side, seeing that `api_sig` parameter was missing to the REST request. Next time you may leave me enough time to come with a patch...

**Comment by Pomax** [comment]
I'll keep that in mind =)

**Comment by akanshgulati** [comment]
@Pomax it will be great if we can mark this thing in bold on README page.

**Comment by Pomax** [comment]
@akanshgulati you mean like is [already the case](https://github.com/Pomax/node-flickrapi#call-functions-that-dont-require-authentication-authenticated-anyway)?
