### ISSUE TITLE
Script does not exit

### ISSUE THREAD

**Issue by neojski** [Pomax/node-flickrapi#63]
`Flickr.authenticate` for some reason never exits.

**Comment by Pomax** [comment]
That... is true, and seems to be true for a lot of versions now. Marking as bug, let's see what's up with that.

**Comment by rschlack** [comment]
I see this problem too.  So was anyone able to authenticate a user completely without having the user have to copy and paste the flickr access token into another window?

**Comment by Pomax** [comment]
That's a completely different issue. If you use the callback URL solution then no one need to copy-paste anything, if you use the oob solution, then you'll need to copy and paste. See the README and the `test.js` example code with minimal callback server.

**Comment by dvdgrdll** [comment]
I am experimenting the same problem. 

We are loading constantly images and it creates a memory leak because every authenticate takes a node and never closes it. Even if a do only one authenticate, it eventually breaks the code.

**Comment by Pomax** [comment]
@dvdgrdll then please *file a new issue* so I can look at that. This issue is about `authenticate()` never returning.
