### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by derwaldgeist** [Pomax/node-flickrapi#66]
Hi, thanks a lot for this great library. Yet, I'm wondering what the license is, since there is none specified? Is it allowed to use it in commercial projects, e.g. under the MIT license?

PS: I'm new to GitHub. If there should be another way to ask questions like these (instead of raising issues), please let me know. :-)

**Comment by Pomax** [comment]
nope, you asked your question in exactly the right way =)

The code's MIT licensed, as indicated in its package.json: https://github.com/Pomax/node-flickrapi/blob/master/package.json#L23

**Comment by derwaldgeist** [comment]
@Pomax: Thanks a lot for your quick reply! MIT is great, thanks again for your efforts.
