### ISSUE TITLE
Unable to `new Flickr`

### ISSUE THREAD

**Issue by cheapsteak** [Pomax/node-flickrapi#71]
`require('flickrapi')` returns an object, and trying to initialize a new Flickr instance like this:

``` js
var Flickr = require('flickrapi');
var flickr = new Flickr({
    api_key: "1234ABCD1234ABCD1234ABCD1234ABCD",
    progress: false
});
```

results in error "object is not a function"

**Comment by Pomax** [comment]
hm, that's a documentation bug. The `Flickr` object has several functions that create an actual API object for you to use, with several different authentication calls possible. I'll have to update the README.md to reflect that -- the procedure in https://github.com/Pomax/node-flickrapi#authenticated-full-flickr-api-access is the correct way to use the Flickr object

**Comment by cheapsteak** [comment]
In that case, is there a way to say that I'm "done" with an instance?  
Currently after `Flickr.tokenOnly`, node won't exit unless I manually call `process.exit()`

**Comment by Pomax** [comment]
hmm, once all callbacks resolve Node should see it has nothing left to keep open and the process should automatically end. If that is not the case, that's a (separate) bug that should get looked at.

**Comment by karlpokus** [comment]
@cheapsteak @Pomax Can confirm. Node hangs. Is a bug.

**Comment by Pomax** [comment]
it's not a bug, but it's a poor design choice that should be handled differently. At this point the Flickr-api code is in need of an ES6 and "using packages that didn't exist at the time that solve the same things this does, better" overhaul.

**Comment by anediaz** [comment]
I've created a reactjs project via 'react-create-app'.
I try to create an instance of Flickr-api but I have an error : 
__WEBPACK_IMPORTED_MODULE_0_flickrapi_browser_flickrapi_js___default.a is not a constructor


This is the code I used to do it :

import Flickr from 'flickrapi/browser/flickrapi.js';
var flickr = new Flickr({
    api_key: FLICKR.api_key
});

And 'FLICKR.api_key' is a constant I defined.
What am I doing wrong? Is it related with the need of an ES6 you talked about in last comment?

**Comment by Pomax** [comment]
It is: you're using an ES6 import statement for an ES5 file that create a global `Flickr` object for pure loading in the browser (i.e. not bundling). It has no `export` instructions anywhere, so that won't work. Instead, tell webpack that there is a global called `Flickr`, and load the browser library with a normal script tag followed by your bundle.

**Comment by aeroxy** [comment]
So I am assuming "new Flickr()" is simply not possible? Then why is it still in the documentation? Remove it.

**Comment by Pomax** [comment]
So I'm assuming you know how to write? Then why is it still a comment instead of a PR? File it.

(or, "I'm not working on this at the moment but will happily merge in a PR. And maybe in some next issue, be a little more polite - you're always talking to fellow human beings, not employees who owe you anything")

**Comment by taniko13** [comment]
Hi Pomax,
I'm a junior developer and I want to use your library to use flickr via React.
I read you answer Anediaz, but I don't understand what I need to do, could you please explain to me more detailed? thanks.

**Comment by Pomax** [comment]
For web work: load the library as a normal page script (using `<script src="..."></script>` before you load your app), don't bundle it in. And in your webpack config, use `webpack.providePlugin` to tell webpack that there is a global variable called `Flickr` (see https://webpack.js.org/plugins/provide-plugin).

For app work: use Node's `require`, not `import`.

**Comment by taniko13** [comment]
Thank you a lot
