### ISSUE TITLE
Flickr API slow

### ISSUE THREAD

**Issue by tedcurrent** [Pomax/node-flickrapi#74]
Hey,

I don't know if this is an issue on Flickr's side, but for some reason I get very weird behaviour with this. Here's a stub from my code:
```
flickr.tokenOnly(flickrOptions, function(err, flickr) {
	if (err) { throw new Error(err); }
	console.log("search pictures");
	flickr.photos.search({
		text: searchParam,
		page: 1,
		per_page: 50,
		sort: "relevance",
		media: "photos",
		extras: "original_format, owner_name",
		min_upload_date: 1274745600 // 25.5.2010
	}, function(err, result) {
		console.log("got pictures");
		var photos = result.photos;
	});
});
```
Sometimes I get response times of around 600ms, but sometimes it's around 7000ms. I've narrowed it down to certainly be between printing "search pictures" and "got pictures". I have a callback that returns the result photos, but I have removed it as it is not relevant. First I thought maybe something is left hanging, but no. Even the first search can be slow. The searchParam is some simple text like "hammer" or "nature".

Any ideas how to get this faster?

Cheers!

/tedcurrent

**Comment by Pomax** [comment]
flickr will rate limit you if you do lots of calls, so that could be part of it. Are you running searches one after another?

**Comment by tedcurrent** [comment]
I could be running approx. 5 calls within 10 seconds. So nothing too hardcore, I assume? Of course if this is nothing you haven't encountered, I start to wonder what could be wrong with my call. Any suggestion would help.

**Comment by Pomax** [comment]
According to https://www.flickr.com/services/developer/api/ the rate limit is 3600 per hour, so 5 calls in 10 seconds shouldn't hit that. One thing that might be affecting it is the date filtering - but that's about it. The code looks pretty normal to me otherwise.

**Comment by tedcurrent** [comment]
Alright. Thanks for the reply. I'll just try to figure out some other options then.

**Comment by Pomax** [comment]
no, server vs. client should matter all that much. oauth vs api-key-only might, but again I kind of doubt it. It could be Flickr simply deciding to actually perform soft rate limiting anyway... does the browser console's profiling reveal anything?

**Comment by tedcurrent** [comment]
<img width="934" alt="screen shot 2016-02-12 at 19 11 12" src="https://cloud.githubusercontent.com/assets/7895034/13014436/7604826a-d1bc-11e5-9a9f-69c0b8b5844d.png">

This is what I get. So most of the time is spent in waiting.. It might be some soft limiting though. I did 5 fast fetches (first fetches today) and on the sixth it jumped to 8 secs.

**Comment by Pomax** [comment]
I'm going to blame this on Flickr, then =(

**Comment by tedcurrent** [comment]
Yeah it's a hundred percent them at this point. Thanks a lot for helping!

**Comment by Pomax** [comment]
and thanks for digging into it!
