### ISSUE TITLE
Multiple user authentication

### ISSUE THREAD

**Issue by xrrr** [Pomax/node-flickrapi#78]
I am trying to work out a way to enable multiple user login so that I can use this library as a server component on a public website.  I want individual Flickr users to be able to use the website I am building.

At the moment the access token and secret are stored in the server .env file.  I was thinking about making a modification to store the token and secret in a cookie but:
(a) I am new to node so not 100% sure where to start, was thinking about adding an additional option to allow the option to save in either the .env or a cookie.
(b) Wanted to double check that I am not misreading things and there is actually a way to do this today.

Make sense?

**Comment by Pomax** [comment]
Do this the right way: use one instance per user, because credentials should not be shared:
```
users.forEach(user => {
  Flickr.authorize(user.options, (err, flickr) => {
    if (err) {
      return ...;
    }
    user.setFlickrAPI(flickr); // <- and then have kick off that user's "whatever happens" code
  });
});
```

**Comment by xrrr** [comment]
Hi there, I have done a load of research and have found a library called Grant that does the oauth the way I need it to work for my website. Thanks for the help.

**Comment by Pomax** [comment]
depending on the additionals, a fair number of the modules on https://www.npmjs.com/search?q=oauth will work quite well (some more maintained than others) but if you found one that works for you: great!
