### ISSUE TITLE
API is broken

### ISSUE THREAD

**Issue by nkingsley** [Pomax/node-flickrapi#88]
line 314 in utils.js does cleaning on the api response. It appears to be failing to clean some kind of new response.

I changed the line to:
```
body = body.trim().replace(/^\/\*\*\/jsonFlickrApi\(/,'').replace(/\}\)$/,'}');
```

and it's working again

**Comment by Genffy** [comment]
+1 
the origin api res have a new line comment
![image](https://cloud.githubusercontent.com/assets/1506972/16473044/6148fade-3e9c-11e6-9c9c-af7e9067a3e3.png)
https://github.com/Pomax/node-flickrapi/blob/master/src/utils.js#L314
that should use new more power reg or another way to deal this.

**Comment by razdvapoka** [comment]
@nkingsley, @Genffy  Thank you!

**Comment by lchenay** [comment]
+1 thanks for quick find.

**Comment by msmichellegar** [comment]
Have been experiencing issues, and this just saved me! Thanks for figuring that out!

+1000

**Comment by Pomax** [comment]
ah, Flickr. Thanks for finding this, I'll merge in the PR momentarily

**Comment by Pomax** [comment]
v0.5.0 pushed to npm - please let me know if this comes back in some way =)
