### ISSUE TITLE
does API supported URL, streaming, buffer upload ?

### ISSUE THREAD

**Issue by wahengchang** [Pomax/node-flickrapi#93]
does API supported URL, streaming, buffer upload ?

As the document mentioned, the only way to upload is local file (by local path "./file")

And we are building a service which given a URL link and upload to Flickr

Any idea ?

**Comment by Pomax** [comment]
can't say I do. I don't know if Flickr even supports streamed uploads. This code is mostly for working with the plain REST API, which by definition means streams are out of the question (streams are pretty much the opposite of RESTful)

**Comment by wahengchang** [comment]
thx man, I found a lib which support buffer, readable streamthat upload, and provided by this cool guy: 
https://www.npmjs.com/package/flickr-upload

and now I am turning it to support URL download , converting image from URL to readasteam and then upload it

**Comment by Pomax** [comment]
nice!
