### ISSUE TITLE
Returned photo results are insufficient, photo property only contains five photo objects when there are clearly more photos

### ISSUE THREAD

**Issue by mikuya707** [Pomax/node-flickrapi#97]
With correct authentication, upon calling 

```
flickr.photos.getContactsPhotos({
  api_key: "XXXXXXXXXXX",
  count: 50,
  extras: "original_format"
}, function(err, result) {
// result is Flickr's response
    var photos = result.photos.photo;
console.log('photos result', result);
  photos.forEach(function(photo){    
    var url = "https://farm" + photo.farm + ".staticflickr.com/" + photo.server + "/" + photo.id + "_" + photo.originalsecret + "_o.jpg";;
    console.log('url is', url);
    download(url, date + "_" + photo.id + ".jpg", function(){
          console.log('done');
          });
    
      // console.log('what are sizes of photos', original);
  })

```
The photo result is print in console as below:
```
photos result { photos:
   { photo: [ [Object], [Object], [Object], [Object], [Object] ],
     total: 5,
     page: 1,
     per_page: 50,
     pages: 1 },
  stat: 'ok' }
```

In this case, there is only one contact, and the contact clearly has more than 10 pages of photos available, why is it only returning 5? I have also tried calling other methods like getPhotos, etc, they all returned 5 in total. Is there a parameter needs to be set in order to receive correct result or something is wrong here? Please advise.

**Comment by Pomax** [comment]
What happens if you try the same parameters on Flickr's online API test for this function call, https://www.flickr.com/services/api/explore/flickr.photos.getContactsPhotos ?

**Comment by mikuya707** [comment]
@Pomax  It returns the same results, only 5 photos.

**Comment by Pomax** [comment]
if the official API route returns the same result, then there isn't much I can do; the flickr.com tests are basically "what Flickr thinks you should get" so this might be a case of needing to figure out which arguments Flickr needs for your specific search to get the results you need (possibly involving a different API route)
